# Create full conda environment for development, including some useful tools
name: mkdocs-unidata
channels:
  - conda-forge
dependencies:
  - python=2.7
  - mkdocs==0.16.3
  - pygments==2.2.0
  - pip
  - pip:
    - pymdown-extensions==4.0
    - fontawesome_markdown==0.2.6
